Added project page
rcos/Telescope pull request #279
Opened 2022-10-11 20:48 UTC by LeadFreeCandy

Added the projects page, as well as pages for individual projects that gives a little info about the project.

2022-10-11 20:52 UTC, bepvte commented
Fixes #12

2022-10-11 20:53 UTC, bepvte commented
#12

2022-10-11 22:27 UTC, Alfriadox requested changes

2022-10-11 22:27 UTC, Alfriadox commented on src/main.rs
> +    .expect("Could not bind http://localhost:8080")
This seems like it will break things. Why change the default port to bind on?

2022-10-18 20:30 UTC, bepvte approved these changes

2022-10-21 20:20 UTC, merged